import React, {useState} from "react";

export const QuestionsInfo = {
    id: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"],
    name: ["Interval List Intersections", "Non-overlapping Intervals", "Meeting Rooms II", "Number of Islands", "K Closest Points to Origin", "Two Sum", "Longest Substring Without Repeating Characters", "Three Sum", "Best Time to Buy and Sell Stock", "Contains Duplicate", "Product of Array Except Self", "Task Scheduler", "Find the Difference", "Jump Game", "Unique Email Addresses", "Keys and Rooms", "Maximal Square", "Reverse Linked List", "Edit Distance", "Maximum Depth of a Binary Tree", "First Unique Character in a String", "Happy Number", "Container With Most Water", "Cheapest Flights Within K Stops", "Binary Tree Maximum Path Sum", "Pairs of Songs With Total Durations Divisible by 60", "Linked List Cycle II", "Richest Customer Wealth", "Detect Capital", "String to Integer (atoi)"],
    link: ["https://leetcode.com/problems/interval-list-intersections/", "https://leetcode.com/problems/non-overlapping-intervals/", "https://leetcode.com/problems/meeting-rooms-ii/", "https://leetcode.com/problems/number-of-islands/", "https://leetcode.com/problems/k-closest-points-to-origin/", "https://leetcode.com/problems/two-sum/", "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "https://leetcode.com/problems/3sum/", "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "https://leetcode.com/problems/contains-duplicate/", "https://leetcode.com/problems/product-of-array-except-self/", "https://leetcode.com/problems/task-scheduler/", "https://leetcode.com/problems/find-the-difference/", "https://leetcode.com/problems/jump-game/", "https://leetcode.com/problems/unique-email-addresses/", "https://leetcode.com/problems/keys-and-rooms/", "https://leetcode.com/problems/maximal-square/", "https://leetcode.com/problems/reverse-linked-list/", "https://leetcode.com/problems/edit-distance/", "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "https://leetcode.com/problems/first-unique-character-in-a-string/", "https://leetcode.com/problems/happy-number/", "https://leetcode.com/problems/container-with-most-water/", "https://leetcode.com/problems/cheapest-flights-within-k-stops/", "https://leetcode.com/problems/binary-tree-maximum-path-sum/", "https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/", "https://leetcode.com/problems/linked-list-cycle-ii", "https://leetcode.com/problems/richest-customer-wealth/", "https://leetcode.com/problems/detect-capital/", "https://leetcode.com/problems/string-to-integer-atoi/"],
    youtube_link: ["https://www.youtube.com/watch?v=EsuaXBQh4hs", "https://www.youtube.com/watch?v=7GDcCBaohVQ", "https://www.youtube.com/watch?v=kZfHnsrQcP0", "https://www.youtube.com/watch?v=d-Fh4DESMss", "https://www.youtube.com/watch?v=z0dgkQ91lkQ", "https://www.youtube.com/watch?v=mK1_vjxMfh4", "https://www.youtube.com/watch?v=w-dBC1n_4ZA", "https://www.youtube.com/watch?v=joefteuIfqg", "https://www.youtube.com/watch?v=cmX-3jx7qE4", "https://www.youtube.com/watch?v=to_beq5bI2c", "https://www.youtube.com/watch?v=6AP9LsNU-q0", "https://www.youtube.com/watch?v=CHlCkJadQ7o", "https://www.youtube.com/watch?v=qsrmeOn7NrE", "https://www.youtube.com/watch?v=fA_4_LuVpZ8", "https://www.youtube.com/watch?v=kGCSaAfe3mk", "https://www.youtube.com/watch?v=gU8raekRs1E", "https://www.youtube.com/watch?v=DoUnpJqclz4", "https://www.youtube.com/watch?v=hhUpMimY0Dw", "https://www.youtube.com/watch?v=j0NNHhWFIQY", "https://www.youtube.com/watch?v=8Rni-r-akSk", "https://www.youtube.com/watch?v=2aAP-CMn_Ao", "https://www.youtube.com/watch?v=b0PC0-NRCxw", "https://www.youtube.com/watch?v=5HU0iQ1wlMo", "https://www.youtube.com/watch?v=vWgoPTvQ3Rw", "https://www.youtube.com/watch?v=5Erye7G3FQU", "https://www.youtube.com/watch?v=gMtxNQHy388", "https://www.youtube.com/watch?v=gWv_D_iBQBk", "https://www.youtube.com/watch?v=_WKJX77JpYY", "https://www.youtube.com/watch?v=vpsyUjqQLms", "https://www.youtube.com/watch?v=qZoFJKyHQ98"],
    difficulty: ["Hard", "Hard", "Hard", "Hard", "Hard", "Easy", "Hard", "Hard", "Easy", "Easy", "Medium", "Medium", "Easy", "Medium", "Easy", "Medium", "Medium", "Easy", "Hard", "Easy", "Easy", "Easy", "Medium", "Medium", "Hard", "Medium", "Medium", "Easy", "Easy", "Medium"],
    completed: [false, false]
}